### PR TITLE
Create hybrid-installation.md

### PR DESCRIPTION
**Pull request by onemoz**
First version of a hybrid local installation rocketpool+hyperdrive side by side

### CODE REVIEW

**Comment by VVander** [comment]
Hey @onemoz thanks for the submission. We don't want to encourage anyone to install other software next to a Rocket Pool installation, however (or next to a Hyperdrive installation, either). If you want to resubmit this guide using isolated environments, feel free.

**Comment by onemoz** [comment]
Hey @VVander! 

Thanks for considering my PR! 

> We don't want to encourage anyone to install other software next to a Rocket Pool installation, 

Fair enough. What if we put a big warning `only for testnet`, or a please do not use this for mainnet?

If this is not advise for both of them, then is there any other use case for the `Additional Docker Networks` parameter?

> If you want to resubmit this guide using isolated environments, feel free.

Which kind of isolation would be acceptable here? 
- RocketPool and HyperDrive in different VMs on the same host? 
- RocketPool installed on the host using docker, and HyperDrive inside a VM on this host? Or inside a LXC/systemd-nspawn? 
- Or both of them using different physical hosts? 

Thank you in advance.

**Comment by VVander** [comment]
Np, thanks for contributing @onemoz!

> Fair enough. What if we put a big warning `only for testnet`, or a please do not use this for mainnet?

We don't want to encourage anyone to do something on testnet that they shouldn't do on mainnet, so it's best to avoid this entirely. 

> If this is not advise for both of them, then is there any other use case for the `Additional Docker Networks` parameter?

This parameter is mostly used for this purpose, but we don't support or encourage running external software inside the same docker network (or inside the same environment at all) as Hyperdrive. The option exists, but it's not something we want to encourage. It's a "do this at your own risk" option.

> Which kind of isolation would be acceptable here?
> 
>     * RocketPool and HyperDrive in different VMs on the same host?
This is acceptable since they are generally isolated.

>     * RocketPool installed on the host using docker, and HyperDrive inside a VM on this host? Or inside a LXC/systemd-nspawn?

This is not acceptable because we don't want to encourage anyone running software next to a RP smartnode or Hyperdrive instance.

>     * Or both of them using different physical hosts?

This is acceptable (and is ideal) because it represents maximum separation. If you want to write a guide for this, I recommend using this scenario because it's the simplest and most secure.

**Comment by onemoz** [comment]
Thank you for your feedback :) I'll be working on this at some point then.

**Pull request closed without merging**
